GET localhost:4000/api/comment/post/637eecdca1c162a6784952b5

###
GET localhost:4000/api/comment/637eecdca1c162a6784952ba

###
POST localhost:4000/api/comment
Content-Type: application/json

{
    "username": "Monty_Wolf",
    "postId": "637eecdca1c162a6784952b5",
    "message": "You’re fabulous ❤️"
}

###
DELETE localhost:4000/api/comment/63803444d4d61f60654ae17c