GET localhost:4000/api/follow/follower-names/demo

###
GET localhost:4000/api/follow/follower-names/demoo

###
POST localhost:4000/api/follow/follow
Content-Type: application/json

{
    "follower": "demo",
    "following": "Carmelo_Pagac1"
}

###
POST localhost:4000/api/follow/follow
Content-Type: application/json

{
  "following": "Carmelo_Pagac1"
}

###
POST localhost:4000/api/follow/unfollow
Content-Type: application/json

{
  "follower": "demo",
  "following": "Carmelo_Pagac1"
}

###
GET localhost:4000/api/follow/is-following/demo/Carmelo_Pagac1

###
GET localhost:4000/api/follow/suggestions/demo

###
GET localhost:4000/api/follow/follow-count/demo