GET http://localhost:4000/api/user/demo

###
GET http://localhost:4000/api/user/Abby.Champlin901

###
PUT http://localhost:4000/api/user/Abby.Champlin901
Content-Type: application/json

{
  "username": "Abby.Champlin901",
  "firstName": "Talon1111",
  "lastName": "Altenwerth1",
  "email": "Casey42@gmail.com",
  "password": "hT2uE1HybohrizE",
  "profilePicture": "https://ui-avatars.com/api/?rounded=true",
  "createdAt": "2022-11-24T05:45:30.104Z",
  "updatedAt": "2022-11-24T05:45:30.104Z",
  "_id": "637f04fa2e1859404ce817c0"
}

###
POST http://localhost:4000/api/user
Content-Type: application/json

{
  "username": "Abby.Champlin901",
  "firstName": "Talon1",
  "lastName": "Altenwerth1",
  "email": "Casey42@gmail.com",
  "password": "hT2uE1HybohrizE",
  "profilePicture": "https://ui-avatars.com/api/?rounded=true"
}

###
DELETE http://localhost:4000/api/user/Abby.Champlin901
